import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./common/Header";
import Sidebar from "./common/Sidebar";
import MainContext from "./MainContext/MainContext";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">

      <body className={inter.className}>
          <MainContext>
              {children}
          </MainContext>
        
      </body>
    </html>
  );
}
